# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/cloudformation

    steps:
      - checkout

      # Download and install awscli
      - run: sudo apt-get -y -qq update
      - run: sudo apt-get -y -qq install python3.4-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: python3.4 get-pip.py --user
      - run: echo 'export PATH=~/.local/bin:$PATH'  >> $BASH_ENV
      - run: source $BASH_ENV
      - run: pip install awscli --upgrade --user

      - run: aws cloudformation update-stack --stack-name hyou --template-body file://00_main.yaml --parameters file://aws-stack-parameters.json --region ap-northeast-1 --capabilities CAPABILITY_IAM

      # run tests!
      - run: yarn test
